# Generated by Django 5.2.5 on 2025-08-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('country_of_origin', models.CharField(max_length=55)),
                ('year_founded', models.PositiveSmallIntegerField()),
                ('founder', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(upload_to='brand_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=55, unique=True)),
                ('year_of_issue', models.PositiveSmallIntegerField()),
                ('staff', models.CharField(choices=[('OD', 'Official dealer'), ('NOD', 'Not official dealer')], max_length=10)),
                ('drive', models.CharField(choices=[('RWD', 'Rear wheel drive'), ('FWD', 'Front wheel drive'), ('AWD', 'All wheel drive')], max_length=10)),
                ('transmissions', models.CharField(choices=[('MT', 'Manual Transmission'), ('AT', 'Automatic Transmission'), ('CVT', 'Continuously Variable Transmission'), ('DCT', 'Dual Clutch Transmission')], max_length=10)),
                ('engine', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=10)),
                ('body_type', models.CharField(choices=[('SD', 'Sedan'), ('HB', 'Hatchback'), ('SUV', 'SUV'), ('CP', 'Coupe'), ('CT', 'Convertible'), ('ET', 'Estate'), ('CR', 'Crossover'), ('MPV', 'Multi-Purpose Vehicle'), ('PT', 'Pickup Truck'), ('Van', 'Van')], max_length=10)),
                ('engine_volume', models.FloatField(help_text='Объем двигателя в литрах')),
                ('engine_power', models.IntegerField(help_text='Мощность двигателя в лошадиных силах (HP)')),
                ('acceleration', models.FloatField(help_text='Разгон 0-100 км/ч (сек)')),
                ('maximum_speed', models.IntegerField(help_text='Максимальная скорость (км/ч)')),
                ('weight', models.IntegerField(help_text='Масса автомобиля (кг)')),
                ('price', models.FloatField(help_text='Цена автомобиля в долларах США')),
                ('price_negotiable', models.BooleanField()),
                ('photo', models.ImageField(upload_to='car_photos/')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalon_app.brands')),
            ],
        ),
    ]
